version: "3.8"

services:
  museum:
    build:
      context: server
      args:
        GIT_COMMIT: local
    # Remove port mapping, Caddy will proxy this
    depends_on:
      postgres:
        condition: service_healthy

    # Wait for museum to ping pong before starting the webapp.
    healthcheck:
      test: [
          "CMD",
          "echo",
          "1", # I don't know what to put here
        ]
    environment:
      # no need to touch these
      ENTE_DB_HOST: postgres
      ENTE_DB_PORT: 5432
      ENTE_DB_NAME: ente_db
      ENTE_DB_USER: pguser
      ENTE_DB_PASSWORD: pgpass
    env_file:
      - ./.credentials.env
    volumes:
      - custom-logs:/var/logs
      - ./museum.yaml:/museum.yaml:ro
    networks:
      - internal

  web:
    build:
      context: web
    # Remove port mapping, Caddy will proxy this
    depends_on:
      museum:
        condition: service_healthy
    env_file:
      - ./.credentials.env
    networks:
      - internal

  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: ente_db
    # Wait for postgres to be accept connections before starting museum.
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "ente_db", "-U", "pguser"]
      interval: 1s
      timeout: 5s
      retries: 20
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - internal

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - internal
    depends_on:
      - web
      - museum

volumes:
  custom-logs:
  postgres-data:
  caddy_data:
  caddy_config:

networks:
  internal:
